spring:
  mvc:
    async:
      request-timeout: 300000
server:
  port: 5000

app:
  productEndpoints:
    product-base-url: http://localhost:3001/
    similar-products: product/{productId}/similarids
    product-details: product/{productId}
web:
  connection-timeout: 60000
